import { project } from "../types";

export const projects: project[] = [
    {
        title: "Portfolio 2022",
        webpage: "https://wroclawianka.github.io/portfolio-ts/",
        repo: "https://github.com/wroclawianka/portfolio-ts",
        stack: ['React', 'Redux', 'TypeScript'],
        description: 'Personal portfolio webpage',
        year: '2022',
    },
    {
        title: "Vote for me",
        webpage: "https://wroclawianka.github.io/vote-for-me/",
        repo: "https://github.com/wroclawianka/vote-for-me",
        stack: ['React', 'Redux', 'TypeScript'],
        description: 'App to create the survey, submit it, and see the results with the graphs',
        year: '2022',
    },
    {
        title: "Groceries List",
        repo: "https://github.com/wroclawianka/groceries-app",
        yt: 'https://youtu.be/r-y8D6FmHk0',
        stack: ['React', 'Redux', 'NodeJS', 'MongoDB'],
        description: 'CRUD app to manage shopping list of a company',
        year: '2020',
    },
    {
        title: "Crypto Tracker",
        webpage: 'https://wroclawianka.github.io/crypto-tracker',
        repo: "https://github.com/wroclawianka/crypto-tracker",
        stack: ['Angular', 'ngrx', 'Material UI'],
        description: 'Cryptocurrency price tracker',
        year: '2020',
    },
    {
        title: "Phonebook",
        repo: "https://github.com/wroclawianka/phonebook",
        yt: 'https://youtu.be/UWDnyAftJW4',
        stack: ['React', 'MongoDB', 'NodeJS'],
        description: 'Full-stack phonebook application with possibility to add, read, edit and delete entries',
        year: '2019',
    },
        {
        title: "Sorting Algorithms",
        webpage: 'https://sorting-algorithms-app.netlify.com/',
        repo: 'https://github.com/wroclawianka/sorting',
        description: 'Visualization of sorting algorithms',
        stack: ['React', 'TypeScript', 'Bootstrap'],
        year: '2019',
    },
    // {
    //     title: "Portfolio 2019",
    //     webpage: "https://wroclawianka.github.io/portfolio",
    //     repo: "https://github.com/wroclawianka/portfolio",
    //     stack: ['React', 'JavaScript', 'HTML/CSS'],
    //     description: 'Personal portfolio webpage',
    //     year: '2019',
    // },
    // {
    //     title: "PWorkshop website 2.",
    //     webpage: 'https://wroclawianka.github.io/workshop-modern/',
    //     repo: 'https://github.com/wroclawianka/workshop-modern',
    //     description: 'Webpage of an unexisting service company',
    //     stack: ['jQuery', 'JavaScript', 'HTML/CSS'],
    //     year: '2018',
    // },
    // {
    //     title: "Loan Ratings App",
    //     webpage: 'https://wroclawianka.github.io/loan-ratings-app/',
    //     repo: 'https://github.com/wroclawianka/loan-ratings-app',
    //     description: 'App calculating an average amount for loans available on marketplace of a given rating',
    //     stack: ['Angular', 'TypeScript', 'HTML/CSS'],
    //     year: '2018',
    // },
    // {
    //     title: "Prague with my eyes",
    //     webpage: 'https://praha-blog.netlify.com/',
    //     repo: 'https://github.com/wroclawianka/BlogApi/tree/master/Blog2.0/blog2.0',
    //     stack: ['Angular', 'TypeScript', 'HTML/CSS'],
    //     description: 'Template of the livestyle blog with edit mode',
    //     year: '2018',
    // },
    // {
    //     title: "Bookshelf",
    //     webpage: 'https://book-list-dorota-zelga.netlify.com/',
    //     repo: 'https://github.com/wroclawianka/book-list-assignment',
    //     description: "CRUD book list app",
    //     stack: ['React', 'JavaScript', 'HTML/CSS', 'Bootstrap'],
    //     year: '2018',
    // },
    // {
    //     title: "Graphical Dashboard",
    //     webpage: 'https://graphical-dashboard.netlify.com/',
    //     repo: 'https://github.com/wroclawianka/graphical-dashboard',
    //     description: 'Pixel perfect diagrams presenting company results',
    //     stack: ['JavaScript', 'HTML/CSS'],
    //     year: '2018',
    // },
    // {
    //     title: "Ordering App",
    //     repo: 'https://github.com/wroclawianka/ordering-assignment',
    //     yt: 'https://youtu.be/-aCDjMuvmGE',
    //     description: 'CRUD app to place an order of the construction tools',
    //     stack: ['React', 'JavaScript', 'HTML/CSS'],
    //     year: '2018',
    // },
    // {
    //     title: "Portfolio 2018",
    //     webpage: "https://wroclawianka.github.io/portfolio-2018/",
    //     repo: "https://github.com/wroclawianka/portfolio-2018",
    //     description: 'Personal portfolio webpage',
    //     stack: ['jQuery', 'JavaScript', 'HTML/CSS'],
    //     year: '2018',
    // },
    // {
    //     title: "Binary Calculator",
    //     webpage: 'https://wroclawianka.github.io/binary-calculator/',
    //     repo: 'https://github.com/wroclawianka/binary-calculator',
    //     description: 'Binary calculator with validation of the fields',
    //     stack: ['jQuery', 'JavaScript', 'Bootstrap', 'HTML/CSS'],
    //     year: '2018',
    // },
    // {
    //     title: "Workshop Website 1.",
    //     webpage: 'https://wroclawianka.github.io/car-service-webpage/',
    //     repo: 'https://github.com/wroclawianka/car-service-webpage',
    //     description: 'Webpage of an unexisting service company',
    //     stack: ['jQuery', 'JavaScript', 'HTML/CSS'],
    //     year: '2018',
    // },
];