import { project } from "../types";

export const projects: project[] = [
    {
        title: "Portfolio #3",
        webpage: "https://wroclawianka.github.io/portfolio-ts/",
        repo: "https://github.com/wroclawianka/portfolio-ts",
        stack: ['REACT', 'REDUX', 'TS', 'HTML/CSS'],
        label: 'React & Redux',
        year: '2022',
    },
    {
        title: "Vote for me",
        webpage: "https://wroclawianka.github.io/vote-for-me/",
        repo: "https://github.com/wroclawianka/vote-for-me",
        stack: ['REACT', 'REDUX', 'TS', 'HTML/CSS'],
        label: 'React & Redux',
        year: '2022',
    },
    {
        title: "Groceries List",
        repo: "https://github.com/wroclawianka/groceries-app",
        yt: 'https://youtu.be/r-y8D6FmHk0',
        stack: ['REACT', 'REDUX', 'NODEJS', 'MONGO', 'MATERIAL UI', 'HTML/CSS'],
        year: '2020',
    },
    {
        title: "Crypto Tracker",
        webpage: 'https://wroclawianka.github.io/crypto-tracker',
        repo: "https://github.com/wroclawianka/crypto-tracker",
        stack: ['ANGULAR', 'NGRX', 'MATERIAL UI', 'HTML/CSS'],
        label: 'Angular & ngrx',
        year: '2020',
    },
    {
        title: "Phonebook",
        repo: "https://github.com/wroclawianka/phonebook",
        yt: 'https://youtu.be/UWDnyAftJW4',
        stack: ['REACT', 'JS', 'MONGO', 'NODEJS', 'MATERIAL UI', 'HTML/CSS'],
        label: 'React & NodeJS',
        year: '2019',
    },
    {
        title: "Sorting Algorithms",
        webpage: 'https://sorting-algorithms-app.netlify.com/',
        repo: 'https://github.com/wroclawianka/sorting',
        stack: ['REACT', 'TS', 'HTML/CSS', 'BOOTSTRAP'],
        year: '2019',
    },
    {
        title: "Portfolio #2",
        webpage: "https://wroclawianka.github.io/portfolio",
        repo: "https://github.com/wroclawianka/portfolio",
        stack: ['REACT', 'JS', 'HTML/CSS'],
        year: '2019',
    },
    {
        title: "Panowie z warsztatu",
        webpage: 'https://wroclawianka.github.io/workshop-modern/',
        repo: 'https://github.com/wroclawianka/workshop-modern',
        stack: ['JQUERY', 'JS', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Loan Ratings App",
        webpage: 'https://wroclawianka.github.io/loan-ratings-app/',
        repo: 'https://github.com/wroclawianka/loan-ratings-app',
        stack: ['ANGULAR', 'TS', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Prague with my eyes",
        webpage: 'https://praha-blog.netlify.com/',
        repo: 'https://github.com/wroclawianka/BlogApi/tree/master/Blog2.0/blog2.0',
        stack: ['ANGULAR', 'TS', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Book List",
        webpage: 'https://book-list-dorota-zelga.netlify.com/',
        repo: 'https://github.com/wroclawianka/book-list-assignment',
        stack: ['REACT', 'JS', 'HTML/CSS', 'BOOTSTRAP'],
        year: '2018',
    },
    {
        title: "Graphical Dashboard",
        webpage: 'https://graphical-dashboard.netlify.com/',
        repo: 'https://github.com/wroclawianka/graphical-dashboard',
        stack: ['JS', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Ordering App",
        repo: 'https://github.com/wroclawianka/ordering-assignment',
        yt: 'https://youtu.be/-aCDjMuvmGE',
        stack: ['REACT', 'JS', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Portfolio #1",
        webpage: "https://wroclawianka.github.io/portfolio-2018/",
        repo: "https://github.com/wroclawianka/portfolio-2018",
        stack: ['JQUERY', 'JS', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Binary Calculator",
        webpage: 'https://wroclawianka.github.io/binary-calculator/',
        repo: 'https://github.com/wroclawianka/binary-calculator',
        stack: ['JQUERY', 'JS', 'BOOTSTRAP', 'HTML/CSS'],
        year: '2018',
    },
    {
        title: "Workshop Website",
        webpage: 'https://wroclawianka.github.io/car-service-webpage/',
        repo: 'https://github.com/wroclawianka/car-service-webpage',
        stack: ['JQUERY', 'JS', 'HTML/CSS'],
        year: '2018',
    },
];